name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.301'
    - name: remove files
      run: |
        rm -f text
      working-directory: /var/www/dotnet_app
    - name: Dotnet Publish
      run: |
       sudo dotnet publish -o /var/www/dotnet_app
      working-directory: /actions-runner/_work/dotnetcore-webapp/dotnetcore-webapp/dotnet-core-webapp
